language: python
python:
  - "3.6"
cache: pip
install:
  - pip install git+https://github.com/hcv-shared/shared-schema@master#egg=shared_schema
  - pip install -e ".[tests]"
script:
  - python setup.py test
  - flake8 shrl test
  - mypy shrl
  - shrl --with-metadata test_data/metadata.conf check test_data
  - shrl --with-metadata test_data/metadta.conf load --init-db --load-regimens "sqlite:///./tmpdb.sqlite"
after_script:
    - rm -f tmpdb.sqlite
notifications:
  email:
    on_failure: change
